---
- name: Install and start webservices
  hosts: all
  become: true
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: latest

    - name: Start the httpd
      service:
        name: httpd
        state: started

